# 2018 #

In [85]:

import pandas as pd
import numpy as np

In [86]:

link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2018"
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [87]:
df = pd.concat([df1,df2,df3,df4],ignore_index=True)

In [88]:
import json
import requests
from typing import Dict,Any
OMDB_API_KEY = '30dbbe0d'

In [89]:
def get_movie_info(title: str) -> Dict[str, Any]:
    url = f"http://www.omdbapi.com/?t={title}&apikey={OMDB_API_KEY}"
    response = requests.get(url)
    data = response.json()
    
    if data['Response'] == 'True':
        return {
            'director_name': data.get('Director', 'unknown'),
            'actor_1_name': data.get('Actors', '').split(', ')[0] if data.get('Actors') else 'unknown',
            'actor_2_name': data.get('Actors', '').split(', ')[1] if len(data.get('Actors', '').split(', ')) > 1 else 'unknown',
            'actor_3_name': data.get('Actors', '').split(', ')[2] if len(data.get('Actors', '').split(', ')) > 2 else 'unknown',
            'genres': data.get('Genre', 'unknown'),
            'movie_title': data.get('Title', 'unknown').lower()
        }
    else:
        return {
            'director_name': 'unknown',
            'actor_1_name': 'unknown',
            'actor_2_name': 'unknown',
            'actor_3_name': 'unknown',
            'genres': 'unknown',
            'movie_title': title.lower()
        }

In [90]:
new_df18 = pd.DataFrame(df['Title'].apply(get_movie_info).tolist())

In [91]:
new_df18['director_name']=new_df18['director_name'].apply(lambda x: x.replace(',',' '))

In [92]:
new_df18['genres']=new_df18['genres'].apply(lambda x: x.replace(',',' '))

In [93]:
new_df18['comb'] = (new_df18['actor_1_name'] + ' ' + 
                    new_df18['actor_2_name'] + ' ' + 
                    new_df18['actor_3_name'] + ' ' + 
                    new_df18['director_name'] + ' ' + 
                    new_df18['genres'])

In [94]:
new_df18

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Adam Robitel,Lin Shaye,Leigh Whannell,Angus Sampson,Horror Mystery Thriller,insidious: the last key,Lin Shaye Leigh Whannell Angus Sampson Adam Ro...
1,Christopher Radcliff Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Crime Drama Mystery,the strange ones,Alex Pettyfer James Freedson-Jackson Emily Alt...
2,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson,Action Mystery Thriller,the commuter,Liam Neeson Vera Farmiga Patrick Wilson Jaume ...
3,Babak Najafi,Taraji P. Henson,Billy Brown,Jahi Di'Allo Winston,Action Crime Drama,proud mary,Taraji P. Henson Billy Brown Jahi Di'Allo Wins...
4,Brett Donowho,Bruce Willis,Cole Hauser,Shawn Ashmore,Action Crime Thriller,acts of violence,Bruce Willis Cole Hauser Shawn Ashmore Brett D...
...,...,...,...,...,...,...,...
243,Peter Segal,Jennifer Lopez,Vanessa Hudgens,Leah Remini,Comedy Drama Romance,second act,Jennifer Lopez Vanessa Hudgens Leah Remini Pet...
244,Guy Ritchie,Robert Downey Jr.,Jude Law,Jared Harris,Action Adventure Mystery,sherlock holmes: a game of shadows,Robert Downey Jr. Jude Law Jared Harris Guy Ri...
245,Adam McKay,Christian Bale,Amy Adams,Steve Carell,Biography Comedy Drama,vice,Christian Bale Amy Adams Steve Carell Adam McK...
246,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux,Biography Drama,on the basis of sex,Felicity Jones Armie Hammer Justin Theroux Mim...
247,Karyn Kusama,Nicole Kidman,Toby Kebbell,Tatiana Maslany,Action Crime Drama,destroyer,Nicole Kidman Toby Kebbell Tatiana Maslany Kar...

In [95]:
unknown_counts =((new_df18 == 'unknown') | new_df18.isna()).sum()
unknown_counts

director_name    1
actor_1_name     1
actor_2_name     1
actor_3_name     1
genres           1
movie_title      0
comb             0
dtype: int64

In [96]:
df_18_cleaned = new_df18[~(new_df18 == 'unknown').any(axis=1)]
df_18_cleaned

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Adam Robitel,Lin Shaye,Leigh Whannell,Angus Sampson,Horror Mystery Thriller,insidious: the last key,Lin Shaye Leigh Whannell Angus Sampson Adam Ro...
1,Christopher Radcliff Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Crime Drama Mystery,the strange ones,Alex Pettyfer James Freedson-Jackson Emily Alt...
2,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson,Action Mystery Thriller,the commuter,Liam Neeson Vera Farmiga Patrick Wilson Jaume ...
3,Babak Najafi,Taraji P. Henson,Billy Brown,Jahi Di'Allo Winston,Action Crime Drama,proud mary,Taraji P. Henson Billy Brown Jahi Di'Allo Wins...
4,Brett Donowho,Bruce Willis,Cole Hauser,Shawn Ashmore,Action Crime Thriller,acts of violence,Bruce Willis Cole Hauser Shawn Ashmore Brett D...
...,...,...,...,...,...,...,...
243,Peter Segal,Jennifer Lopez,Vanessa Hudgens,Leah Remini,Comedy Drama Romance,second act,Jennifer Lopez Vanessa Hudgens Leah Remini Pet...
244,Guy Ritchie,Robert Downey Jr.,Jude Law,Jared Harris,Action Adventure Mystery,sherlock holmes: a game of shadows,Robert Downey Jr. Jude Law Jared Harris Guy Ri...
245,Adam McKay,Christian Bale,Amy Adams,Steve Carell,Biography Comedy Drama,vice,Christian Bale Amy Adams Steve Carell Adam McK...
246,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux,Biography Drama,on the basis of sex,Felicity Jones Armie Hammer Justin Theroux Mim...
247,Karyn Kusama,Nicole Kidman,Toby Kebbell,Tatiana Maslany,Action Crime Drama,destroyer,Nicole Kidman Toby Kebbell Tatiana Maslany Kar...

In [109]:
unknown_counts =((df_18_cleaned == 'unknown') | df_18_cleaned.isna()).sum()
unknown_counts

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

# 2019

In [98]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2019"
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [99]:
df = pd.concat([df1,df2,df3,df4],ignore_index=True)

In [100]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,J A N U A R Y,4,Escape Room,Columbia Pictures / Original Film,"Adam Robitel (director); Bragi F. Schut, Maria...",[2]
1,J A N U A R Y,4,Rust Creek,IFC Films / Lunacy Productions,Jen McGowan (director); Julie Lipson (screenpl...,[3]
2,J A N U A R Y,4,American Hangman,Hangman Justice Productions,Wilson Coneybeare (director/screenplay); Donal...,[4]
3,J A N U A R Y,11,A Dog's Way Home,Columbia Pictures,Charles Martin Smith (director); W. Bruce Came...,[5]
4,J A N U A R Y,11,The Upside,STX Entertainment,Neil Burger (director); Jon Hartmere (screenpl...,[6]
...,...,...,...,...,...,...
245,D E C E M B E R,25,Spies in Disguise,20th Century Fox Animation / Blue Sky Studios ...,"Nick Bruno, Troy Quane (directors); Brad Copel...",[133]
246,D E C E M B E R,25,Little Women,Columbia Pictures / Regency Enterprises,Greta Gerwig (director/screenplay); Saoirse Ro...,[226]
247,D E C E M B E R,25,1917,Universal Pictures / DreamWorks Pictures,Sam Mendes (director/screenplay); Krysty Wilso...,[227]
248,D E C E M B E R,25,Just Mercy,Warner Bros. Pictures / Participant Media,"Destin Daniel Cretton (director/screenplay), A...",[228]
249,D E C E M B E R,27,Clemency,Neon,Chinonye Chukwu (director/screenplay); Alfre W...,[229]

In [101]:
new_df19 = pd.DataFrame(df['Title'].apply(get_movie_info).tolist())

In [102]:
new_df19['director_name']=new_df19['director_name'].apply(lambda x: x.replace(',',' '))

In [103]:
new_df19['genres']=new_df19['genres'].apply(lambda x: x.replace(',',' '))

In [104]:
new_df19['comb'] = (new_df19['actor_1_name'] + ' ' + 
                    new_df19['actor_2_name'] + ' ' + 
                    new_df19['actor_3_name'] + ' ' + 
                    new_df19['director_name'] + ' ' + 
                    new_df19['genres'])

In [105]:
unknown_counts =((new_df19 == 'unknown') | new_df19.isna()).sum()
unknown_counts

director_name    1
actor_1_name     1
actor_2_name     4
actor_3_name     4
genres           1
movie_title      0
comb             0
dtype: int64

In [106]:
df_19_cleaned = new_df19[~(new_df19 == 'unknown').any(axis=1)]
df_19_cleaned

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Adam Robitel,Taylor Russell,Logan Miller,Jay Ellis,Action Adventure Horror,escape room,Taylor Russell Logan Miller Jay Ellis Adam Rob...
1,Jen McGowan,Hermione Corfield,Jay Paulson,Sean O'Bryan,Action Crime Drama,rust creek,Hermione Corfield Jay Paulson Sean O'Bryan Jen...
2,Wilson Coneybeare,Donald Sutherland,Vincent Kartheiser,Oliver Dennis,Crime Mystery Thriller,american hangman,Donald Sutherland Vincent Kartheiser Oliver De...
3,Charles Martin Smith,Ashley Judd,Jonah Hauer-King,Edward James Olmos,Adventure Drama Family,a dog's way home,Ashley Judd Jonah Hauer-King Edward James Olmo...
4,Neil Burger,Kevin Hart,Bryan Cranston,Nicole Kidman,Comedy Drama,the upside,Kevin Hart Bryan Cranston Nicole Kidman Neil B...
...,...,...,...,...,...,...,...
245,Nick Bruno Troy Quane,Rachel Brosnahan,Jarrett Bruno,Claire Crosby,Animation Action Adventure,spies in disguise,Rachel Brosnahan Jarrett Bruno Claire Crosby N...
246,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,Drama Romance,little women,Saoirse Ronan Emma Watson Florence Pugh Greta ...
247,Sam Mendes,Dean-Charles Chapman,George MacKay,Daniel Mays,Action Drama History,1917,Dean-Charles Chapman George MacKay Daniel Mays...
248,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson,Biography Crime Drama,just mercy,Michael B. Jordan Jamie Foxx Brie Larson Desti...
249,Chinonye Chukwu,Alfre Woodard,Richard Schiff,Aldis Hodge,Drama,clemency,Alfre Woodard Richard Schiff Aldis Hodge Chino...

In [111]:
unknown_counts =((df_19_cleaned == 'unknown') | df_19_cleaned.isna()).sum()
unknown_counts

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [115]:
df2018_2019=pd.concat([df_18_cleaned,df_19_cleaned],ignore_index=True)

In [123]:
old_df = pd.read_csv('new_data.csv')
unknown_counts =((old_df == 'unknown') | old_df.isna()).sum()
unknown_counts

director_name    102
actor_1_name       7
actor_2_name      13
actor_3_name      23
genres             0
movie_title        0
comb               0
dtype: int64

In [125]:
old_df_cleaned = old_df[~(old_df == 'unknown').any(axis=1)]
old_df_cleaned

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,Avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,Pirates of the Caribbean: At World's End,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,Spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,The Dark Knight Rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
5,Andrew Stanton,Daryl Sabara,Samantha Morton,Polly Walker,Action Adventure Sci-Fi,John Carter,Daryl Sabara Samantha Morton Polly Walker Andr...
...,...,...,...,...,...,...,...
5370,Jim Strouse,Jessica Williams,Chris O'Dowd,Keith Stanfield,Romance Comedy,the incredible jessica james,Jessica Williams Chris O'Dowd Keith Stanfield ...
5371,Farhad Mann,Adelaide Kane,Benjamin Hollingsworth,Jean Louisa Kelly,Romance,can't buy my love,Adelaide Kane Benjamin Hollingsworth Jean Loui...
5372,Hannaleena Hauru,Inka HaapamÃ¤ki,Rosa Honkonen,Tiitus Rantala,Romance Comedy,thick lashes of lauri mÃ¤ntyvaara,Inka HaapamÃ¤ki Rosa Honkonen Tiitus Rantala Ha...
5373,Jonathan A. Rosenbaum,Lou Diamond Phillips,Wallace Shawn,Gina Holden,Crime Comedy Action Family,cop and a half: new recruit,Lou Diamond Phillips Wallace Shawn Gina Holden...
5374,Ravi Udyawar,Sridevi Kapoor,Sajal Ali,Akshaye Khanna,Crime Drama Thriller,mom,Sridevi Kapoor Sajal Ali Akshaye Khanna Ravi U...

In [127]:
df_upto2019=pd.concat([old_df_cleaned,df2018_2019],ignore_index=True)
df_upto2019

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,Avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,Pirates of the Caribbean: At World's End,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,Spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,The Dark Knight Rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Andrew Stanton,Daryl Sabara,Samantha Morton,Polly Walker,Action Adventure Sci-Fi,John Carter,Daryl Sabara Samantha Morton Polly Walker Andr...
...,...,...,...,...,...,...,...
5741,Nick Bruno Troy Quane,Rachel Brosnahan,Jarrett Bruno,Claire Crosby,Animation Action Adventure,spies in disguise,Rachel Brosnahan Jarrett Bruno Claire Crosby N...
5742,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,Drama Romance,little women,Saoirse Ronan Emma Watson Florence Pugh Greta ...
5743,Sam Mendes,Dean-Charles Chapman,George MacKay,Daniel Mays,Action Drama History,1917,Dean-Charles Chapman George MacKay Daniel Mays...
5744,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson,Biography Crime Drama,just mercy,Michael B. Jordan Jamie Foxx Brie Larson Desti...
5745,Chinonye Chukwu,Alfre Woodard,Richard Schiff,Aldis Hodge,Drama,clemency,Alfre Woodard Richard Schiff Aldis Hodge Chino...

In [129]:
((df_upto2019 == 'unknown') | df_upto2019.isna()).sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [131]:
df_upto2019.to_csv('datupto2019.csv',index=False)

# 2020 #

In [134]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2020"
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [136]:
df = pd.concat([df1,df2,df3,df4],ignore_index=True)

In [138]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,J A N U A R Y,3,The Grudge,Screen Gems / Stage 6 Films / Ghost House Pict...,Nicolas Pesce (director/screenplay); Andrea Ri...,[2]
1,J A N U A R Y,10,Underwater,20th Century Fox / TSG Entertainment / Chernin...,"William Eubank (director); Brian Duffield, Ada...",[3]
2,J A N U A R Y,10,Like a Boss,Paramount Pictures / Artists First,"Miguel Arteta (director); Sam Pitman, Adam Col...",[4]
3,J A N U A R Y,10,Three Christs,IFC Films,Jon Avnet (director/screenplay); Eric Nazarian...,NaN
4,J A N U A R Y,10,Inherit the Viper,Lionsgate / Barry Films / Tycor International ...,Anthony Jerjen (director); Andrew Crabtree (sc...,[5]
...,...,...,...,...,...,...
271,D E C E M B E R,25,We Can Be Heroes,Netflix / Troublemaker Studios / Double R Prod...,Robert Rodriguez (director/screenplay); Priyan...,[244]
272,D E C E M B E R,25,News of the World,Universal Pictures / Playtone / Perfect World ...,Paul Greengrass (director/screenplay); Luke Da...,[245]
273,D E C E M B E R,25,One Night in Miami...,Amazon Studios,Regina King (director); Kemp Powers (screenpla...,[246]
274,D E C E M B E R,25,Promising Young Woman,Focus Features / FilmNation Entertainment,Emerald Fennell (director/screenplay); Carey M...,[247]
275,D E C E M B E R,30,Pieces of a Woman,Netflix / Bron Studios,KornÃ©l MundruczÃ³ (director); Kata WÃ©ber (scree...,[248]

In [140]:
new_df20 = pd.DataFrame(df['Title'].apply(get_movie_info).tolist())

In [142]:
new_df20['director_name']=new_df20['director_name'].apply(lambda x: x.replace(',',' '))

In [143]:
new_df20['genres']=new_df20['genres'].apply(lambda x: x.replace(',',' '))

In [144]:
new_df20['comb'] = (new_df20['actor_1_name'] + ' ' + 
                    new_df20['actor_2_name'] + ' ' + 
                    new_df20['actor_3_name'] + ' ' + 
                    new_df20['director_name'] + ' ' + 
                    new_df20['genres'])

In [149]:
unknown_counts =((new_df20 == 'unknown') | new_df20.isna()).sum()
unknown_counts

director_name    4
actor_1_name     4
actor_2_name     4
actor_3_name     4
genres           4
movie_title      0
comb             0
dtype: int64

In [151]:
df_20_cleaned = new_df20[~(new_df20 == 'unknown').any(axis=1)]
df_20_cleaned

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Takashi Shimizu,Sarah Michelle Gellar,Jason Behr,Clea DuVall,Horror Mystery Thriller,the grudge,Sarah Michelle Gellar Jason Behr Clea DuVall T...
1,William Eubank,Kristen Stewart,Vincent Cassel,Mamoudou Athie,Action Horror Sci-Fi,underwater,Kristen Stewart Vincent Cassel Mamoudou Athie ...
2,Miguel Arteta,Tiffany Haddish,Rose Byrne,Salma Hayek,Comedy,like a boss,Tiffany Haddish Rose Byrne Salma Hayek Miguel ...
3,Jon Avnet,Richard Gere,Peter Dinklage,Bradley Whitford,Drama,three christs,Richard Gere Peter Dinklage Bradley Whitford J...
4,Anthony Jerjen,Tara Buck,Margarita Levieva,Lobo Sebastian,Action Crime Mystery,inherit the viper,Tara Buck Margarita Levieva Lobo Sebastian Ant...
...,...,...,...,...,...,...,...
271,Robert Rodriguez,YaYa Gosselin,Pedro Pascal,Priyanka Chopra Jonas,Action Comedy Drama,we can be heroes,YaYa Gosselin Pedro Pascal Priyanka Chopra Jon...
272,Paul Greengrass,Tom Hanks,Helena Zengel,Tom Astor,Action Adventure Drama,news of the world,Tom Hanks Helena Zengel Tom Astor Paul Greengr...
273,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge,Drama,one night in miami...,Kingsley Ben-Adir Eli Goree Aldis Hodge Regina...
274,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie,Crime Drama Mystery,promising young woman,Carey Mulligan Bo Burnham Alison Brie Emerald ...
275,KornÃ©l MundruczÃ³,Vanessa Kirby,Shia LaBeouf,Ellen Burstyn,Drama,pieces of a woman,Vanessa Kirby Shia LaBeouf Ellen Burstyn KornÃ©...

In [153]:
unknown_counts =((df_20_cleaned == 'unknown') | df_20_cleaned.isna()).sum()
unknown_counts

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [157]:
upto2019_df = pd.read_csv('datupto2019.csv')

In [159]:
df_upto2020=pd.concat([upto2019_df,df_20_cleaned],ignore_index=True)
df_upto2020

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,Avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,Pirates of the Caribbean: At World's End,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,Spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,The Dark Knight Rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Andrew Stanton,Daryl Sabara,Samantha Morton,Polly Walker,Action Adventure Sci-Fi,John Carter,Daryl Sabara Samantha Morton Polly Walker Andr...
...,...,...,...,...,...,...,...
6013,Robert Rodriguez,YaYa Gosselin,Pedro Pascal,Priyanka Chopra Jonas,Action Comedy Drama,we can be heroes,YaYa Gosselin Pedro Pascal Priyanka Chopra Jon...
6014,Paul Greengrass,Tom Hanks,Helena Zengel,Tom Astor,Action Adventure Drama,news of the world,Tom Hanks Helena Zengel Tom Astor Paul Greengr...
6015,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge,Drama,one night in miami...,Kingsley Ben-Adir Eli Goree Aldis Hodge Regina...
6016,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie,Crime Drama Mystery,promising young woman,Carey Mulligan Bo Burnham Alison Brie Emerald ...
6017,KornÃ©l MundruczÃ³,Vanessa Kirby,Shia LaBeouf,Ellen Burstyn,Drama,pieces of a woman,Vanessa Kirby Shia LaBeouf Ellen Burstyn KornÃ©...

In [163]:
df_upto2020.to_csv('datupto2020.csv',index=False)